services:
  - type: web
    name: likeplusvietnam
    env: static
    buildCommand: npm ci --only=production && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false 