services:
  - type: web
    name: likeplusvietnam
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.x 